apiVersion: apps/v1
kind: Deployment
metadata:
  name: sit323-2025-prac5p-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sit323-2025-prac5p-app
  template:
    metadata:
      labels:
        app: sit323-2025-prac5p-app
    spec:
      containers:
        - name: sit323-2025-prac5p-app
          image: ovinnawarathne/sit323-2025-prac5p-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password
            - name: MONGO_HOST
              value: mongo-service
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_DB
              value: calculatorDB
