version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: 5.1P
    restart: always
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      MONGO_USER: admin
      MONGO_PASSWORD: password
      MONGO_HOST: mongo        # references the MongoDB service by its service name
      MONGO_PORT: "27017"
      MONGO_DB: calculatorDB

volumes:
  mongo-data:
