apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongo-backup
spec:
  # This schedule runs daily at 2 AM (change as needed)
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mongo-backup
              image: mongo:latest
              command:
                - bash
                - -c
                - >
                  mongodump --host mongo-service --username $MONGO_USER --password $MONGO_PASSWORD --authenticationDatabase admin --out /backup/$(date +\%F)
              env:
                - name: MONGO_USER
                  valueFrom:
                    secretKeyRef:
                      name: mongo-secret
                      key: mongo-user
                - name: MONGO_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mongo-secret
                      key: mongo-password
              volumeMounts:
                - name: backup-storage
                  mountPath: /backup
          restartPolicy: OnFailure
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: backup-pvc
