apiVersion: v1
kind: Service
metadata:
  name: sit323-2025-prac5p-app-service
spec:
  type: NodePort
  selector:
    app: sit323-2025-prac5p-app
  ports:
    - protocol: TCP
      port: 80 # External port
      targetPort: 8080 # Container's port
